import Link from "next/link"
import PublicInfoPage from "@/components/public-info-page"
import { pageMetadata } from "@/lib/metadata"
export const metadata = pageMetadata("Data & Editorial Policy", "How GAMEBOX separates source-backed facts, editorial assessments and algorithmic recommendations.", "/data-policy")
export default function DataPolicyPage() {
  return <PublicInfoPage title="DATA & EDITORIAL POLICY">
    <section><h2>FACTUAL DATA</h2><p>Each published game has field-level sources for its title, earliest listed release year, development and publishing credits, and listed platforms. Game pages link to recorded source revisions and show the review date. The versioned evidence audit stores extracted metadata and normalization decisions.</p><p>Most factual metadata is checked against the game&apos;s Wikipedia infobox. Return of the Obra Dinn&apos;s development credit also uses its developer-published Steam listing. Verification means agreement with the cited source, not independent archival research or endorsement of every claim in that source.</p><p>Years use the earliest release listed across regions. Platform lists may include ports, editions and remasters; they do not establish current availability, compatibility or distribution permission.</p></section>
    <section><h2>GAMEBOX EDITORIAL DATA</h2><p>Experience, Mood, Genre, Gameplay, Pacing, Structure, Perspective and Difficulty are editorial interpretations. Era is derived from the sourced year. Descriptions, recommendation copy and playtime estimates are editorial. “Not assessed” means no playtime estimate has been made.</p><p>Gamebox, Hidden Gem, Retro and Revival Potential scores are provisional editorial signals. Some records start from shared classification profiles; these are not individual reviews, aggregate critic scores, user ratings or verified popularity/sales measurements. Hidden Gem is not proof that a game is obscure.</p></section>
    <section><h2>GAMEBOX RECOMMENDATIONS</h2><p>Finder MATCH % measures coverage of selected preferences; search and platform narrow candidates. Similarity compares recorded DNA, with identity weighted more than context and uncommon shared traits providing more evidence. Neither percentage is a probability of enjoyment or an objective quality score.</p><p>Confidence bands describe recorded overlap: 80–100 Very Strong, 65–79 Strong, 50–64 Good, 35–49 Partial, below 35 Limited. Labels use rounded similarity percentages. Sparse or incomplete editorial classification can produce imperfect results.</p><p>BEST MATCH uses semantic relevance only. HIDDEN GEM considers its editorial rating after a hard relevance requirement. SURPRISE ME is deterministic and remains tied to shared distinctive DNA. Ratings never enter the semantic similarity percentage. A missing mode means no candidate cleared its requirements.</p></section>
    <section><h2>Corrections and limitations</h2><p>The archive contains 100 selected games and has coverage gaps. Source availability and editorial assessments can change. For a correction, identify the game, disputed field and supporting source through our <Link href="/contact">contact page</Link>.</p></section>
  </PublicInfoPage>
}
