// Editorial picks and copy. Factual fields are populated from cited source infoboxes.
// Existing game identities and URLs remain stable.
module.exports = [
  ["Portal", "Portal_(video_game)", "puzzle", "Solve spatial puzzles with two linked portals while a dryly sarcastic machine tests your trust."],
  ["Portal 2", "Portal_2", "puzzle", "Explore abandoned test chambers and combine portals with gels, beams and cooperative problem solving."],
  ["Half-Life", "Half-Life_(video_game)", "shooter", "A laboratory disaster becomes a continuous journey through tightly connected encounters and environmental puzzles."],
  ["Half-Life 2", "Half-Life_2", "shooter", "Physics-driven combat and a journey through occupied cities turn the environment into your toolkit."],
  ["BioShock", "BioShock", "immersive", "Explore an underwater city where powers, scarce resources and environmental stories shape each encounter."],
  ["BioShock 2", "BioShock_2", "immersive", "Return to Rapture with heavy weapons, defensive encounters and a different perspective on its damaged society."],
  ["BioShock Infinite", "BioShock_Infinite", "shooter", "Fight through a floating city with aerial movement, strange powers and an uneasy partnership."],
  ["Dishonored", "Dishonored", "stealth", "Choose routes through a plague-stricken city using supernatural movement, careful observation and flexible assassination tools."],
  ["Dishonored 2", "Dishonored_2", "stealth", "Experiment with two protagonists and intricate spaces that reward patient exploration and inventive stealth."],
  ["Fallout", "Fallout_(video_game)", "rpg", "Leave the vault and navigate a wasteland where character choices and conversations carry lasting consequences."],
  ["Fallout 2", "Fallout_2", "rpg", "Build a distinct wasteland survivor and explore settlements with competing interests and unusual solutions."],
  ["Fallout: New Vegas", "Fallout:_New_Vegas", "rpg", "Choose allegiances in the Mojave and resolve conflicts through conversation, exploration or combat."],
  ["Baldur's Gate", "Baldur%27s_Gate_(video_game)", "rpg", "Lead an adventuring party through wilderness, cities and a mystery grounded in character-driven role playing."],
  ["Baldur's Gate II: Shadows of Amn", "Baldur%27s_Gate_II:_Shadows_of_Amn", "rpg", "Manage a rich party of companions and explore quests that intertwine relationships with tactical combat."],
  ["Planescape: Torment", "Planescape:_Torment", "rpg", "Investigate identity and memory through unusual companions, philosophical conversations and a strange city of portals."],
  ["Disco Elysium", "Disco_Elysium", "narrative", "Investigate a murder while your own competing thoughts reshape conversations, clues and your sense of self."],
  ["The Elder Scrolls III: Morrowind", "The_Elder_Scrolls_III:_Morrowind", "rpg", "Explore an unfamiliar island through directions, faction rivalries and a character you develop at your own pace."],
  ["The Elder Scrolls IV: Oblivion", "The_Elder_Scrolls_IV:_Oblivion", "rpg", "Wander Cyrodiil, join guilds and follow a collection of quests ranging from intimate mysteries to large-scale threats."],
  ["The Elder Scrolls V: Skyrim", "The_Elder_Scrolls_V:_Skyrim", "rpg", "Build your own route through a mountainous open world filled with dungeons, factions and dragon encounters."],
  ["The Witcher 3: Wild Hunt", "The_Witcher_3:_Wild_Hunt", "rpg", "Track monsters and people through an open world of difficult choices and carefully written side stories."],
  ["Mass Effect", "Mass_Effect_(video_game)", "rpg", "Assemble a crew and investigate a galactic threat through conversation, exploration and squad combat."],
  ["Mass Effect 2", "Mass_Effect_2", "rpg", "Recruit specialists and build their trust before undertaking a dangerous mission with your assembled crew."],
  ["Dragon Age: Origins", "Dragon_Age:_Origins", "rpg", "Shape a party and an alliance through tactical encounters, origin stories and difficult political choices."],
  ["Vampire: The Masquerade – Bloodlines", "Vampire:_The_Masquerade_%E2%80%93_Bloodlines", "rpg", "Navigate nocturnal Los Angeles with clan-specific abilities, social choices and a tangled supernatural hierarchy."],
  ["Arx Fatalis", "Arx_Fatalis", "immersive", "Explore an underground world with rune-casting magic, practical experimentation and interconnected spaces."],
  ["Gothic", "Gothic_(video_game)", "rpg", "Earn a place in a prison colony whose factions and dangerous wilderness make early survival feel tangible."],
  ["S.T.A.L.K.E.R.: Shadow of Chernobyl", "S.T.A.L.K.E.R.:_Shadow_of_Chernobyl", "shooter", "Explore a hazardous zone where tense gunfights, strange anomalies and scavenging create an uncertain journey."],
  ["Metro 2033", "Metro_2033_(video_game)", "shooter", "Travel through underground settlements and dangerous surface routes with limited supplies and an oppressive atmosphere."],
  ["Dead Space", "Dead_Space_(2008_video_game)", "horror", "Navigate a failing spacecraft and carefully dismember threats while sound and cramped spaces keep pressure high."],
  ["Alien: Isolation", "Alien:_Isolation", "horror", "Hide, improvise and manage noise aboard a station where a persistent alien changes your plans."],
  ["Amnesia: The Dark Descent", "Amnesia:_The_Dark_Descent", "horror", "Explore a decaying castle with limited means of defense and a growing uncertainty about your past."],
  ["SOMA", "SOMA_(video_game)", "horror", "Investigate an underwater facility where unsettling encounters frame questions about consciousness and identity."],
  ["Signalis", "Signalis", "horror", "Balance inventory, puzzles and scarce resources in a surreal science-fiction world built around memory and longing."],
  ["Resident Evil", "Resident_Evil_(1996_video_game)", "horror", "Explore a mansion through locked routes, limited supplies and discoveries that slowly reveal the disaster inside."],
  ["Resident Evil 4", "Resident_Evil_4_(2005_video_game)", "horror", "Manage space and ammunition in tense encounters that combine precision shooting with constant forward pressure."],
  ["Silent Hill", "Silent_Hill_(video_game)", "horror", "Search a fog-bound town for a missing child while ordinary streets give way to disturbing spaces."],
  ["Silent Hill 4: The Room", "Silent_Hill_4:_The_Room", "horror", "Investigate a locked apartment and unsettling alternate spaces in a horror story about intrusion and isolation."],
  ["Eternal Darkness: Sanity's Requiem", "Eternal_Darkness", "horror", "Follow interwoven historical stories while a sanity system questions what you can trust on screen."],
  ["Parasite Eve", "Parasite_Eve_(video_game)", "rpg", "Investigate a biological nightmare in New York with a compact blend of role playing and positional combat."],
  ["Dino Crisis", "Dino_Crisis_(video_game)", "horror", "Investigate an isolated research facility where swift dinosaurs turn resource decisions and corridors into immediate threats."],
  ["Chrono Trigger", "Chrono_Trigger", "rpg", "Travel through eras with a memorable party and connected events that reshape a time-spanning adventure."],
  ["Final Fantasy VI", "Final_Fantasy_VI", "rpg", "Follow an ensemble cast through a world where personal stories and large-scale upheaval reshape your party."],
  ["Final Fantasy VII", "Final_Fantasy_VII", "rpg", "Explore a planet under industrial pressure and customize a party through a flexible materia system."],
  ["Final Fantasy IX", "Final_Fantasy_IX", "rpg", "Journey with a varied cast through a storybook world concerned with identity, belonging and mortality."],
  ["Final Fantasy X", "Final_Fantasy_X", "rpg", "Follow a pilgrimage through Spira with turn-based battles that emphasize party switching and tactical decisions."],
  ["Suikoden II", "Suikoden_II", "rpg", "Recruit a large cast and build a base while friendship and political conflict drive a war story."],
  ["Xenogears", "Xenogears", "rpg", "Alternate martial-arts battles and giant-machine combat through an ambitious story of identity, power and belief."],
  ["EarthBound", "EarthBound", "rpg", "Explore an everyday world made strange by humor, psychic powers and an unusually warm sense of adventure."],
  ["Paper Mario: The Thousand-Year Door", "Paper_Mario:_The_Thousand-Year_Door", "rpg", "Combine theatrical turn-based combat, paper transformations and distinctive companions in a playful treasure hunt."],
  ["The Legend of Zelda: Ocarina of Time", "The_Legend_of_Zelda:_Ocarina_of_Time", "adventure", "Explore Hyrule across two periods and solve dungeons that connect tools, music and spatial understanding."],
  ["The Legend of Zelda: Majora's Mask", "The_Legend_of_Zelda:_Majora%27s_Mask", "adventure", "Learn a town's repeating routines and use transformations to resolve stories within a three-day cycle."],
  ["The Legend of Zelda: The Wind Waker", "The_Legend_of_Zelda:_The_Wind_Waker", "adventure", "Sail between islands in a colorful world whose small discoveries connect to larger dungeon adventures."],
  ["Super Metroid", "Super_Metroid", "metroidvania", "Read an interconnected alien world and use new abilities to uncover routes with minimal explicit guidance."],
  ["Metroid Prime", "Metroid_Prime", "metroidvania", "Investigate an alien environment through scanning, first-person exploration and abilities that open interconnected routes."],
  ["Castlevania: Symphony of the Night", "Castlevania:_Symphony_of_the_Night", "metroidvania", "Explore an expanding castle with new movement abilities, varied equipment and secrets behind familiar rooms."],
  ["Super Mario 64", "Super_Mario_64", "platformer", "Experiment with expressive movement across compact three-dimensional playgrounds filled with stars and secret routes."],
  ["Super Mario World", "Super_Mario_World", "platformer", "Explore branching stages with precise jumps, rideable companions and exits that reward experimentation."],
  ["Donkey Kong Country", "Donkey_Kong_Country", "platformer", "Navigate rhythmic platforming stages with distinct environments, animal companions and carefully hidden bonuses."],
  ["Banjo-Kazooie", "Banjo-Kazooie_(video_game)", "platformer", "Explore themed worlds using an expanding moveset and a playful collection of characters, puzzles and collectibles."],
  ["Psychonauts", "Psychonauts", "platformer", "Enter imaginative mental worlds whose visual ideas and platforming challenges reflect the characters who inhabit them."],
  ["Ōkami", "%C5%8Ckami", "adventure", "Restore a stylized world with brush techniques that connect combat, puzzles and expressive interactions."],
  ["Beyond Good & Evil", "Beyond_Good_%26_Evil_(video_game)", "adventure", "Investigate a conspiracy through photography, exploration and stealth alongside a small group of allies."],
  ["Prince of Persia: The Sands of Time", "Prince_of_Persia:_The_Sands_of_Time", "adventure", "Cross intricate spaces with acrobatic movement and a rewind mechanic that encourages careful experimentation."],
  ["Jet Set Radio", "Jet_Set_Radio", "arcade", "Skate through a stylized city and paint graffiti while balancing movement, routes and pursuit."],
  ["Crazy Taxi", "Crazy_Taxi_(video_game)", "arcade", "Turn a city into a timed driving challenge by finding passengers and taking inventive routes."],
  ["Rez", "Rez_(video_game)", "arcade", "Match shooting and movement to an evolving audiovisual rhythm in abstract on-rails environments."],
  ["Panzer Dragoon Saga", "Panzer_Dragoon_Saga", "rpg", "Explore a strange world through flight and tactical battles built around positioning a dragon."],
  ["Skies of Arcadia", "Skies_of_Arcadia", "rpg", "Explore floating islands with sky pirates, recruit allies and combine party battles with airship encounters."],
  ["Metal Gear Solid", "Metal_Gear_Solid_(1998_video_game)", "stealth", "Infiltrate a military facility through observation, unusual encounters and a story that repeatedly questions your mission."],
  ["Metal Gear Solid 3: Snake Eater", "Metal_Gear_Solid_3:_Snake_Eater", "stealth", "Blend into jungle environments, manage survival and adapt to stealth encounters with varied equipment."],
  ["Tom Clancy's Splinter Cell: Chaos Theory", "Splinter_Cell:_Chaos_Theory", "stealth", "Use light, sound and flexible routes to infiltrate spaces that reward patient observation."],
  ["Hitman: Blood Money", "Hitman:_Blood_Money", "stealth", "Read social spaces and arrange elaborate assassinations through disguises, accidents and carefully timed opportunities."],
  ["Hollow Knight", "Hollow_Knight", "metroidvania", "Explore a ruined underground kingdom whose demanding fights and hidden paths gradually reveal its history."],
  ["Celeste", "Celeste_(video_game)", "platformer", "Climb a mountain through precise, rapidly retryable platforming challenges paired with a story of self-acceptance."],
  ["Hades", "Hades_(video_game)", "roguelike", "Build changing combat combinations across escape attempts while repeated conversations deepen relationships in the underworld."],
  ["Outer Wilds", "Outer_Wilds", "exploration", "Investigate a small solar system where knowledge and curiosity unlock a mystery across repeating cycles."],
  ["Return of the Obra Dinn", "Return_of_the_Obra_Dinn", "puzzle", "Reconstruct a ship's fate by connecting frozen scenes, identities and evidence through careful deduction."],
  ["Undertale", "Undertale", "rpg", "Meet unusual monsters and choose how to handle encounters in a story responsive to your decisions."],
  ["Stardew Valley", "Stardew_Valley", "cozy", "Build a farm, learn local routines and balance friendships, exploration and small daily goals."],
  ["Journey", "Journey_(2012_video_game)", "exploration", "Travel through a vast desert toward a distant mountain with wordless encounters and expressive movement."],
];
